export const RECEIVE_USER_EVENTS = "GITHUB_RECEIVE_USER_EVENTS";
export const REQUEST_USER_EVENTS = "GITHUB_REQUEST_USER_EVENTS";
export const TOGGLE_ORG_FILTER = "TOGGLE_ORG_FILTER";
export const TOGGLE_REPO_FILTER = "TOGGLE_REPO_FILTER";
export const SET_DATE_FILTER = "SET_DATE_FILTER";